### ISSUE TITLE
Per-atom descriptors 

### ISSUE THREAD

**Issue by exapde** [ACEsuit/ACE.jl#108]
Is there a way to obtain per-atom descriptors from ACE.jl? By "per-atom descriptors", I mean the values of the local descriptors at every atom site before summing them up to obtain the global descriptors.

**Comment by cortner** [comment]
yes that is fairly easy to do, but we don't provide a convenient interface at the moment. If you tell me a little bit what your application is, then I can also suggest whether should use ACE.jl or ACE1.jl which is much better tested and more user-friendly at the moment. I can then also put together a user interface for per-atom descriptors, with your input.

**Comment by exapde** [comment]
I am interested in comparing ACE potential with SNAP and SOAP for hafnium oxidation. With SNAP, I can get all the descriptors and derivatives. However, I don't know how to obtain the descriptors with ACE.jl, even though I were able to run the example https://acesuit.github.io/ACE1docs.jl/dev/tutorials/developing/. Of course, the descriptors must be computed somewhere in your code. If you can point me where they are computed, I appreciate your help.

**Comment by cortner** [comment]
ok, I'll put together a PR for ACE1 asap.

**Comment by cortner** [comment]
actually looking through the codes we do have it *ALMOST* implemented: 

https://github.com/JuliaMolSim/JuLIP.jl/blob/68e1f987ba7f51fc1145870cbc99b2718da38f1f/src/mlips.jl#L289

Once you have an ACE basis `basis`, say, and an atoms object `at` you could simply define 
```Julia
site_energies(basis::IPBasis, at::Atoms) = site_energy.(Ref(basis), Ref(at), 1:length(at))
site_energies_d(basis::IPBasis, at::Atoms) = site_energy_d.(Ref(basis), Ref(at), 1:length(at))
```
or something along those lines. (I didn't test it) The first line would define the per-atom descriptors you want, while the second line would give you the derivatives w.r.t. to the local sites. This might not be a particularly effective data layout since it uses vectors of vectors of vectors .... but it should "just work" and will let you test it at least, and show you how to write a more efficient scheme if you wish. I'm happy to help with that of course.

**Comment by cortner** [comment]
One important thing to keep in mind here is that we do not yet provide sensible defaults. Probably best to ping myself and @casv2 on ACE-Slack to discuss how to choose the parameters.

**Comment by cortner** [comment]
Please close this if you are happy with this, otherwise let me know what else you need.

**Comment by exapde** [comment]
Thank you very much. Your suggestion is very helpful. Just another question 

energy(shipB::IPBasis, at::AbstractAtoms{T})

**Comment by cortner** [comment]
yes and then sum them up. That's the definition of total energy. forces are analogous.

**Comment by exapde** [comment]
You are great help! I'll keep you posted about my experiences/any results with ACE.

**Comment by cortner** [comment]
looking forward to hearing it!
