### ISSUE TITLE
JuLIP compatibility

### ISSUE THREAD

**Issue by davkovacs** [ACEsuit/ACE.jl#34]
currently the Project.toml says ACE is not compatible with JuLIP version 0.11.2, which is the default JuLIP. This causes conflicts and prevent installation. When I add this version of JuLIP everything seems to work fine.

**Comment by cortner** [comment]
thanks for flagging this. I've now tested that ACE 0.8.x and latest JuLIP (with mt) work ok together  -- which is actually a surprise for me since I've made some pretty significant changes to JuLIP to accommodate ACE2.  :)

So I've fixed the version numbers so next time you update you should get the latest JuLIP automatically. (or as soon as I've tagged it anyhow...)

**Comment by cortner** [comment]
if the problem is solved, please reopen it
